#define IDH_APPLICATION_MENU  6
#define IDH_APPLICATION_TOOLBAR  7
#define IDH_WELCOME  3
#define IDH_ADDING_TOPICS  12
#define IDH_FILE_MENU  14
#define IDH_INTRODUCTION  4
#define IDH_PHRASE_BROWSER  8
#define IDH_REMOVE_TOPICS  13
#define IDH_EDIT_MENU  15
#define IDH_OVERVIEW  5
#define IDH_PHRASE_EXTRACTION_DIALOG  10
#define IDH_TOOLS_MENU  16
#define IDH_EXTRACTING_PHRASES  19
#define IDH_TOPIC_MANAGER_DIALOG  9
#define IDH_HELP_MENU  17
#define IDH_USING_APPLICATION_FUNCTIONS  18
#define IDH_EXPORTING_PHRASES  11

